Don't fail when yaml is invalid
screwdriver-cd/config-parser pull request #16
Opened 2016-10-12 04:43 UTC by petey

Converts config-parser to promise interface.
When a parse error occurs, the parser will return a valid config that spits out the error message, and exits with a failure.

2016-10-12 04:47 UTC, d2lam commented on index.js
> +                    image: 'node:4',
Why `node:4`?

2016-10-12 04:49 UTC, d2lam requested changes

2016-10-12 04:49 UTC, d2lam commented on index.js
> +                    steps: [{
shouldn't this be `commands`

2016-10-12 05:08 UTC, petey commented on index.js
> +                    image: 'node:4',
I dunno. I'll change it to `alpine`

2016-10-12 05:08 UTC, petey commented on index.js
> +                    steps: [{
right you are then.

2016-10-12 19:21 UTC, minzcmu approved these changes
👍 
![fellcat](https://cloud.githubusercontent.com/assets/20427140/19324413/53587c8e-9076-11e6-99aa-c65cf05e290a.gif)

2016-10-12 20:08 UTC, stjohnjohnson approved these changes
Looking good! 👍

2016-10-12 20:08 UTC, stjohnjohnson commented on index.js
> +const parseYaml = yaml => (new Promise((resolve) => {
Can you make this one-line?

2016-10-12 20:30 UTC, d2lam approved these changes

2016-10-12 21:45 UTC, FenrirUnbound approved these changes
👍 

Looks good to me

![345t9873154](https://cloud.githubusercontent.com/assets/721148/19328847/88772d66-908a-11e6-8420-e01be1405906.gif)

2016-10-13 00:08 UTC, petey commented on index.js
> +const parseYaml = yaml => (new Promise((resolve) => {
fixed.

2016-10-13 00:30 UTC, merged