fix(hip): Upgrade to node:8
screwdriver-cd/config-parser pull request #61
Opened 2018-04-18 23:21 UTC by ScottyFillups

## Context

Node.js 6 is slowly becoming deprecated, with popular packages such as `semantic-release` no longer supporting it.

## Objective

* Change image in `screwdriver.yaml` to `node:8`
* Update the `engines` property in `package.json`

2018-04-19 18:18 UTC, Filbird approved these changes

2018-04-20 18:20 UTC, minzcmu requested changes

2018-04-20 18:20 UTC, minzcmu commented on test/data/node-module.yaml
> -workflow:
You need requires: [~pr, ~commit] for the main job and [main] for publish job

2018-04-23 17:08 UTC, ScottyFillups commented on test/data/node-module.yaml
> -workflow:
Isn't the `requires` already there?

https://github.com/screwdriver-cd/config-parser/blob/node8/test/data/node-module.yaml#L13
https://github.com/screwdriver-cd/config-parser/blob/node8/test/data/node-module.yaml#L27

2018-04-24 17:45 UTC, minzcmu approved these changes

2018-04-24 18:06 UTC, merged