[DNM] [2] feat(937): Add scmUrls to doc
screwdriver-cd/config-parser pull request #64
Opened 2018-05-25 19:42 UTC by Filbird

Include the `scmUrls` array as part of the object returned by config parser.

Pending: 
 - https://github.com/screwdriver-cd/data-schema/pull/239

https://github.com/screwdriver-cd/screwdriver/issues/937

2018-05-30 22:09 UTC, tkyi commented on test/data/pipeline-with-blocked-by.json
> +                "blockedBy": ["~main", "~sd@123:publish"],
👍

2018-05-30 22:12 UTC, tkyi approved these changes
LGTM 👍 

Might want to explicitly pull in the latest data-schema in package.json and add yourself to the contributing list, but these aren't blocking comments

2018-06-01 18:52 UTC, minzcmu requested changes

2018-06-01 18:52 UTC, minz1027 commented on index.js
> +                scmUrls: Hoek.reach(doc, 'scmUrls', { default: [] }),
Can we make this optional? if `scmUrls` not exist, don't bother to add it to res at all.

2018-06-01 21:57 UTC, minzcmu approved these changes

2018-06-01 21:57 UTC, merged